variableanddatetype
print("ashvik")      
print("Hello Ashvik")
name3=("ashvik")
print("name")
print("name3")
print("a1a1a1a1a1a1a1_ashvik_raj_aaron")
a1a="aaaaaaaaaaaa"
print("ashvik")
#print
#ashvik_raj_aaron_1
print(a1a)
#string
str1="aaaaa"    
str2="ssssss"
str3=(str1 + a1a + str2)
print(str3)
str4='''a_s_h_v_i_k__r_a_j__a_a_r_o_n'''
print(name3,a1a,str1,str2,str3,str4)
print("A")
print("S")
print("H")
print("V")
print("I")
print("K")
print("R")
print("A")
print("J")
print("A")
print("A")
print("R")
print("O")
print("N")
A='A'
S='S'
H='H'
V='V'
I='I'
K='K'
print(A,S,H,V,I,K,a1a,name3,str1,str2,str3,str4)
